name: flutter_weather_app
description: "test task"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: SFProDisplay
      fonts:
        - asset: fonts/sf_pro/SF-Pro-Display-Medium.otf
        - asset: fonts/sf_pro/SF-Pro-Display-Semibold.otf
        - asset: fonts/sf_pro/SF-Pro-Display-Thin.otf
        - asset: fonts/sf_pro/SF-Pro-Display-Regular.otf
    - family: SFCompact
      fonts:
        - asset: fonts/sf_compact/SFCompactText-Light.otf
